title: ALAN
description: Automatically nurture leads via text message and turn them into potential customers. 
timezone: UTC
port: 2000
markdown: kramdown
theme: minima
exclude:
- Gemfile
- Gemfile.lock
sass:
  style: compressed
minima:
  date_format: "%b %-d, %Y"
sass:
  style: compressed

# Pagination
pagination:
  enabled: true # must be set to true
  per_page: 10 # number of posts displayed per page
  permalink: "/page/:num/" # the pagination format
  sort_reverse: true # show the latest post first
# Collections
collections:
  pages:
    output: true # Set to render files in _pages folder
    permalink: /:title/ # Set the format of the permalink by default
  posts:
    permalink: /updates/:title/